apiVersion: apps/v1
kind: Deployment
metadata:
  name: myrecsys1
  labels:
    app: myrecsys1
spec:
  selector:
    matchLabels:
      app: myrecsys1
  template:
    metadata:
      labels:
        app: myrecsys1
    spec:
      containers:
      - name: myrecsys1
        image: kristianastefa/my_recsys1
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: myrecsys1
spec:
  selector:
    app: myrecsys1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer 