apiVersion: apps/v1
kind: Deployment
metadata:
  name: useractivity1
  labels:
    app: useractivity1
spec:
  selector:
    matchLabels:
      app: useractivity1
  template:
    metadata:
      labels:
        app: useractivity1
    spec:
      containers:
      - name: useractivity1
        image: kristianastefa/useractivity1
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: useractivity1
spec:
  selector:
    app: useractivity1
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 5000
      nodePort: 30000
  type: LoadBalancer 

